#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Harry Vince"
# email = "<email-address>"

[signing]
behavior = "own"
backend = "ssh"
key = "~/.ssh/id_ed25519"

[remotes.origin]
auto-track-bookmarks = "glob:*"

[aliases]
rb = ["rebase", "-b@", "-dmain"]

[templates]
git_push_bookmark = '"f-changes-" ++ change_id.short()'
