[tools]
bun = "latest"
go = "latest"
node = "22"
pnpm = "latest"
pre-commit = "latest"
python = "3.14.1"
terraform = "latest"
tf-summarize = "latest"
tflint = "latest"
uv = "latest"
yq = "latest"
"pipx:pynvim" = "latest"
aws-cli = "latest"
ansible-core = "latest"

[settings]
activate_aggressive = true
experimental = true
idiomatic_version_file = true
