# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  theme:
    selectedLineBgColor: [ "#005f87"]
git:
  overrideGpg: true
  pagers:
    - externalDiffCommand: "difft --color=always --display=inline --syntax-highlight=on --tab-width=2"
